#!/usr/bin/env node
// clone-build.mjs — turn a scout flow-map into a LIVE grammY funnel.
//
//   node scripts/clone-build.mjs ../scout/flow-map.json
//
// Emits src/funnels/cloned.ts (a real grammY conversation reproducing the captured
// screens/branches + any drip follow-ups) and flips src/funnels/active.ts to it, so
// `npm start` runs the clone. It also prints an IDENTITY manifest (name/description
// to apply via apply-identity.mjs; the avatar can only be set in @BotFather — the
// Bot API has no setMyPhoto). Re-running overwrites cloned.ts, never your other code.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dir, "../src/funnels");

const mapPath = process.argv[2];
if (!mapPath) { console.error("usage: node scripts/clone-build.mjs <flow-map.json>"); process.exit(1); }
const map = JSON.parse(readFileSync(mapPath, "utf8"));

const q = (s) => JSON.stringify(String(s ?? ""));

// --- build SCREENS: node key -> { msgs: bubbles[], buttons: [{label,to}] } ------
const screens = {};
for (const [k, n] of Object.entries(map.nodes || {})) {
  const msgs = String(n.text || "").split(/\n\n+/).map((s) => s.trim()).filter(Boolean);
  const seen = new Set();
  const buttons = [];
  for (const b of n.buttons || []) {
    if (b.kind !== "callback" || seen.has(b.text)) continue;   // dedup by label
    seen.add(b.text);
    const edge = (map.edges || []).find((e) => e.from === k && e.button === b.text);
    let to = null;
    if (edge && typeof edge.to === "string" && map.nodes[edge.to]) to = edge.to;   // real next screen
    buttons.push({ label: b.text, to });
  }
  screens[k] = { msgs: msgs.length ? msgs : ["…"], buttons };
}

const drip = (map.drip || []).map((d) => ({
  delaySec: d.delaySec || 0,
  msgs: String(d.text || "").split(/\n\n+/).map((s) => s.trim()).filter(Boolean),
}));

const target = map.target || "?";
const root = map.root && screens[map.root] ? map.root : Object.keys(screens)[0];

// --- emit cloned.ts (mirrors the boilerplate welcome.ts API exactly) -----------
const ts = `// AUTO-GENERATED by clone-build.mjs from a scout flow-map of ${target}.
// It reproduces the captured funnel as a grammY conversation. This is PLAIN CODE —
// edit it freely (rerunning clone-build overwrites only this file). Screens with
// unresolved branches (bot didn't reset during scouting) end the flow; fill them in.
import type { Conversation } from "@grammyjs/conversations";
import { InlineKeyboard } from "grammy";
import type { MyContext } from "../bot.js";
import { recordConversion } from "../features/tracking.js";

type Screen = { msgs: string[]; buttons: { label: string; to: string | null }[] };

const ROOT = ${q(root)};
const SCREENS: Record<string, Screen> = ${JSON.stringify(screens, null, 2)};
export const CLONED_DRIP: { delaySec: number; msgs: string[] }[] = ${JSON.stringify(drip, null, 2)};

export async function cloned(conversation: Conversation<MyContext>, ctx: MyContext) {
  let cur: string | null = ROOT;
  const guard = new Set<string>();
  while (cur && SCREENS[cur] && !guard.has(cur)) {
    guard.add(cur);
    const s: Screen = SCREENS[cur];
    for (let i = 0; i < s.msgs.length; i++) {
      const last = i === s.msgs.length - 1;
      // human pacing: show "typing…", then pause scaled to the line length, THEN
      // send it — so bubbles arrive one-by-one like a person typing, not a wall.
      // The delay is wrapped in conversation.external so grammY's replay runs it once.
      await ctx.replyWithChatAction("typing").catch(() => {});
      const pause = Math.min(2600, 500 + s.msgs[i].length * 22);
      await conversation.external(() => new Promise<void>((r) => setTimeout(r, pause)));
      if (last && s.buttons.length) {
        const kb = new InlineKeyboard();
        s.buttons.forEach((b, j) => kb.text(b.label, \`b_\${j}\`).row());
        await ctx.reply(s.msgs[i], { reply_markup: kb });
      } else {
        await ctx.reply(s.msgs[i]);
      }
    }
    if (!s.buttons.length) break;
    const triggers = s.buttons.map((_, j) => \`b_\${j}\`);
    const cq = await conversation.waitForCallbackQuery(triggers);
    await cq.answerCallbackQuery();
    const j = Number(cq.callbackQuery.data.slice(2));
    await conversation.external(() => recordConversion(ctx.from!.id, "funnel_step"));
    cur = s.buttons[j]?.to ?? null;
  }
  await conversation.external(() => recordConversion(ctx.from!.id, "funnel_complete"));

  // DRIP: delayed follow-ups the scout captured. In-process timers (fine while the
  // bot runs; for restart-proof scheduling move these to a DB + worker later).
  for (const d of CLONED_DRIP) {
    const chatId = ctx.chat!.id;
    setTimeout(() => { d.msgs.forEach((m) => ctx.api.sendMessage(chatId, m).catch(() => {})); }, d.delaySec * 1000);
  }
}
`;

mkdirSync(SRC, { recursive: true });
writeFileSync(resolve(SRC, "cloned.ts"), ts);
writeFileSync(resolve(SRC, "active.ts"),
  `// Switched to the generated clone by clone-build.mjs.\n` +
  `export { cloned as activeFunnel } from "./cloned.js";\nexport const ACTIVE_NAME = "cloned";\n`);

// --- identity manifest (for apply-identity.mjs) --------------------------------
const id = map.identity || {};
const manifest = { name: id.name || null, about: id.about || null, avatar: id.avatar_file || null };
writeFileSync(resolve(SRC, "cloned.identity.json"), JSON.stringify(manifest, null, 2));

const cov = map.coverage || {};
console.log(`✓ cloned funnel written: src/funnels/cloned.ts (${Object.keys(screens).length} screens, ${drip.length} drip)`);
console.log(`✓ active funnel switched to "cloned" — npm run db:push && npm start`);
console.log(`\nIDENTITY to apply → node scripts/apply-identity.mjs`);
console.log(`  name:  ${manifest.name}`);
console.log(`  about: ${(manifest.about || "").slice(0, 80)}`);
console.log(`  avatar: ${manifest.avatar || "(none)"} — set it in @BotFather (Bot API can't set a bot photo)`);
if (cov.reset_supported === false || cov.complete === false || (cov.unreached || []).length) {
  console.log(`\n⚠ PARTIAL capture — tell the user honestly:`);
  (cov.notes || []).forEach((n) => console.log("  • " + n));
  if ((cov.unreached || []).length) console.log("  • не пройдены ветки: " + cov.unreached.join(", "));
}
